### ISSUE TITLE
Domoticz + 2017 s veesion 2.72

### ISSUE THREAD

**Issue by hanspnyholm** [mjiderhamn/worx-landroid-nodejs#15]
I got this error after i updatet the Worx to 2.72.

home/pi/worx/landroid-cloud2domoticz.js:27
    domoticz.setAlert(status.errorMessage ? AlertLevel.RED : AlertLevel.GRAY,
             ^

TypeError: domoticz.setAlert is not a function
    at LandroidCloud.updateListener (/home/pi/worx/landroid-cloud2domoticz.js:27:14)
    at LandroidCloud.onMessage (/home/pi/worx/landroid-cloud.js:234:12)
    at DeviceClient.<anonymous> (/home/pi/worx/landroid-cloud.js:186:16)
    at emitThree (events.js:116:13)
    at DeviceClient.emit (events.js:197:7)
    at MqttClient.<anonymous> (/home/pi/node_modules/aws-iot-device-sdk/device/index.js:749:12)
    at emitThree (events.js:116:13)
    at MqttClient.emit (events.js:197:7)
    at MqttClient._handlePublish (/home/pi/node_modules/aws-iot-device-sdk/node_modules/mqtt/lib/client.js:816:12)
    at MqttClient._handlePacket (/home/pi/node_modules/aws-iot-device-sdk/node_modules/mqtt/lib/client.js:286:12)
pi@raspberrypi:~/worx$

**Comment by MeisterTR** [comment]
pleas activate the colum : https://github.com/mjiderhamn/worx-landroid-nodejs/blob/master/landroid-cloud.js#L201 and post the log. Maybe i can help.

**Comment by hanspnyholm** [comment]
I try that now, but its not saving any log file?

**Comment by hanspnyholm** [comment]
I removed the line that giving the error an just copy mqtt message in terminal.


MQTT message received: {"mac":"888888888888","fw":2.72,"bt":{"t":29.4,"v":19.73,"p":85,"nr":230,"c":0},"dmp":[-1.1,-2.8,5.9],"st":{"b":1915,"d":29622,"wt":2112},"ls":1,"le":0,"lz":4,"rsi":-74,"lk":0}
Landroid status: {"state":"Home","errorMessage":null,"batteryPercentage":null,"totalMowingHours":35.2,"totalDistance":29622,"noOfAlarms":0}

**Comment by hanspnyholm** [comment]
Its anyone looking at this problem.
And in the new version you can se battery status and wifi signal.
Would be great if you can fix that to.

**Comment by mjiderhamn** [comment]
@hanspnyholm , can you post a new MQTT message example?

**Comment by hanspnyholm** [comment]
MQTT message received: {"mac":"F0FE6B208344","fw":2.75,"bt":{"t":16.2,"v":19.36,"p":79,"nr":987,"c":0},"dmp":[-0.6,-0.3,9.6],"st":{"b":5446,"d":87326,"wt":5879},"ls":1,"le":0,"lz":6,"rsi":-70,"lk":0}
Landroid status: {"state":"Home","errorMessage":null,"batteryPercentage":null,"totalMowingHours":98,"totalDistance":87326,"noOfAlarms":0}

**Comment by Bouni** [comment]
I have a WR101SI and see the same output. 
As far as I can tell the values are:

* mac: MAC address
* fw: firmware version 
* bt: battery values
  *  t: temperatur in °C
  * v: voltage
  * p: battery level in %
  * nr: number of charging cycles
  * c: charging in progress 
* dmp: position sensor values
  * [Pitch,Roll,Yaw]
* st: status information
  * b: blade useage in minutes
  * d: total distance driven in meters
  * wt: total work time in minutes
* ls: status code
* le: error code
* lz: ???
* rsi: wifi signal strength in dbm
* lk: ???

Does anyone know how the percentage value that is shown in the app is calculated?

**Comment by MagnusKlingenberg** [comment]
The percentage value is simply how much of the scheduled mowing time has passed.

**Comment by Bouni** [comment]
Ok.
Do you also have an idea if i can subscribe to the CommandIn Topic to see what the app is sending to the mower? I did a Test a while ago but had no success (but maybe I did something wrong)
